### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by mcg-web** [kbond/ZenstruckAssetManifestBundle#1]
Hi,
first thanks for open sourcing this helpful bundle! 
Could you bump a pre-release version please?

**Comment by kbond** [comment]
No problem, glad it helps you! I will create a 1.0.0 tag once I merge #2.

**Comment by kbond** [comment]
https://github.com/kbond/ZenstruckAssetManifestBundle/releases/tag/v1.0.0
