### ISSUE TITLE
A bunch of minor changes/ideas

### ISSUE THREAD

**Issue by trappar** [kbond/ZenstruckAssetManifestBundle#3]
Hey, thanks for making this bundle! Looks like it hasn't really been discovered, but I'm actually finding it to be a great drop-in solution for cache-busting webpack assets using the [webpack-manifest-plugin](https://www.npmjs.com/package/webpack-manifest-plugin). Might want to add that to your readme as a potential use case!

On to the issues. From most important to least important...

1. I'm getting a deprecation warning: "Referencing the "asset" extension by its name (defined by getName()) is deprecated since 1.26 and will be removed in Twig 2.0. Use the Fully Qualified Extension Class Name instead." - should be an easy fix.
2. It seems unnecessary to be doing a separate compiler pass (ParseManifestCompilerPass), when you could do exactly the same stuff from within ZenstruckAssetManifestExtension. I think saving the extra step and inlining that code would make the bundle a bit easier to understand, and it would drop creating an unnecessary parameter.
3. The documentation doesn't say anything about the fact that the `manifest_asset` twig function still uses the `asset` twig function. This is an important detail and should definitely be added!
4. The documentation could do a better job of explaining that `manifest_asset` can be used in all environments. Splitting the docs into a section on a sample dev configuration and a sample prod configuration could potentially improve this. At first I assumed that if no manifest file was provided the twig extension wouldn't work at all, and I ruled out using this bundle because of that. I do see that you mention this in the configuration section, I just don't think it's enough.
5. You could potentially refactor your tests using [matthiasnoback/symfony-dependency-injection-test](https://github.com/matthiasnoback/SymfonyDependencyInjectionTest). Totally unnecessary at this point, but worth looking into if you didn't already know about it.
6. Project structure and composer.json could be refactored a bit. Lately I've been seeing projects that look more like this: [symfony serializer component](https://github.com/symfony/serializer/blob/master/composer.json#L46-L51). I like this structure just because it results in no extra classes being added to the classmap regardless of how you use the library (dev or otherwise).

So... how can I help? If you're open to these ideas I'd be happy to contribute via pull request, or if you'd like to do it yourself that would be awesome too!

**Comment by kbond** [comment]
Hey Jeff, thanks for the critique and suggestions! I'm glad you find the bundle useful. I edited your issue to number the points - see my notes below:
1. Fixed, see #4
2. I can't for the life of me remember why I used a compiler pass - I remember there was a reason but I can't remember what it was (I should really have made some comments!). Anyway it looks like I may have missed the obvious solution and over-complicated the bundle with a compiler pass. I removed it and moved the logic to the extension (see #4) - the tests all pass but if you encounter problems let me know!
3. Could you make a PR for this? Always great to have outside help with the documentation as usage is obvious to me!
4. Could you make a PR for this?
5. I have definitely used that lib before but wanted full functional tests to ensure it worked with the entire framework. If you want to add tests using that lib, feel free to submit a PR.
6. I'm not sure about this one - isn't using `autoload-dev` enough to prevent the test classes from being in the classmap?

Thanks again!
Kevin

**Comment by trappar** [comment]
- 1/2: Excellent! Thanks for making those changes.
- 3/4: I'll go ahead and submit a PR with documentation changes when I get a chance.
- 5: Makes sense.
- 6: The one major difference is that using autoload-dev only excludes test classes when the `--no-dev` flag is used. By default those classes will appear in the classmap, which is not really an issue since it doesn't affect prod, it's just a bit annoying in editors that support completion. Really not a big deal though.

**Comment by kbond** [comment]
Re. 6: Check out https://getcomposer.org/doc/04-schema.md#autoload-dev - `autoload-dev` is only used when it is at the project root. When this library is included as a dependency, the tests folder is not autoloaded. The reason Symfony uses `exclude-from-classmap` is because its tests classes are included in `autoload`.

**Comment by kbond** [comment]
I'm going to close this as I think all the issues have been addressed. If you want to further improve the documentation, feel free to open a PR :)
